### ISSUE TITLE
Get an error about font family "Monterrat-black" not being found

### ISSUE THREAD

**Issue by oscadev** [WrathChaos/react-native-login-screen#1]
Get an error about font family "Monterrat-black" not being found. 

What ive done: Installed all the packages as mentioned in the instructions, and closed metro and relaunched.

**Comment by WrathChaos** [comment]
Hello, I'm working on it. I believed that it should work with the latest version. Can you tell me which version are you working on?

**Comment by WrathChaos** [comment]
Hey again @oscadev, you are right. I fixed the `font family` bug with the new release:

### [Release 0.3.4 😍] (https://github.com/WrathChaos/react-native-login-screen/releases/tag/0.3.4)

**Comment by oscadev** [comment]
Thanks!

**Comment by oscadev** [comment]
New strange issue. So I went and added ".3" in the version in the package.json. When I saved the package.json, it immediately loaded correctly. I thought this was strange that it instantaneously worked like that without reinstalling the package, so I went ahead and redid a yarn install, and it stopped working lol. Now I get "unrecognized font family 'anticon'"

**Comment by WrathChaos** [comment]
That is a `react-native-vector-icons` issue. You should run `react-native link` or you can use `react-native-asset` command with react-native-asset library :)
