### ISSUE TITLE
Unhide password function

### ISSUE THREAD

**Issue by firstChairCoder** [WrathChaos/react-native-login-screen#125]
Hi,

We use this library in our app. Lovely open-source work BTW.

I was wondering if the function of having the password being visible (like the common UI of using the eye) can be made available. I'm asking because I could make a PR on that if it's something you feel the package could find use with.

Thanks. 👍🏾

**Comment by WrathChaos** [comment]
Hello @firstChairCoder 

I love to hear that you're using the library in your app :) 

PR's are always welcome, and I am glad to review it

**Comment by firstChairCoder** [comment]
Nice.
I'll get on it and run it by you shortly 😊

**Comment by WrathChaos** [comment]
Helloooo @firstChairCoder 

Finally, I made the password show/hide feature in the built-in of the library :) 

### [Version 5](https://github.com/WrathChaos/react-native-login-screen/releases/tag/5.0.0) is released 🌟

It supports this feature as well please try it out 🥰
