### ISSUE TITLE
Optional Email Validation

### ISSUE THREAD

**Issue by huperniketes** [WrathChaos/react-native-login-screen#126]
There should be an option to validate the value entered conforms to the email standards (RFCs 6531/6532), and provide visual feedback (eg, red text) to the user if it does not.

It should be optional (eg, a "validateEmail" prop) so the app author could use it to support usernames as well.

If the option is chosen, the "Login" button should be disabled until the email address has been validated.

**Comment by WrathChaos** [comment]
Hello @huperniketes 

Finally optional email validation and even password validation with optional tooltips are here :) 


### [Version 5](https://github.com/WrathChaos/react-native-login-screen/releases/tag/5.0.0) is released 🌟

It should support this feature as well please try it out 🥰
