### ISSUE TITLE
Suggested iterative development workflow?

### ISSUE THREAD

**Issue by huperniketes** [WrathChaos/react-native-login-screen#128]
It seems the default React Native build process doesn't support symlinks, making the standard npm link technique for adding local repos ineffective.

What is your development process for react-native-login-screen? Do you have an alternative process that allows rapid development?

**Comment by WrathChaos** [comment]
Hello @huperniketes 
Really sorry for the extremely late response. 

You can use something like this to test local repos.
```json
"dependencies": {
  "local-package": "file:../your-path/local-package"
}
```


However, to be honest I am not using this method. My best practice is always working on the `example` project and then moving the `lib` outside of the lib and running the proper scripts which I wrote. You can check the scripts on `package.json`. 

Also,

I am using my own boilerplate for creating open-source libraries: https://github.com/WrathChaos/react-native-typescript-library-starter

I totally suggest that :) It covers lots of stuff for a maintainer/creator

If you need further questions, please feel free to ask :)
