### ISSUE TITLE
Add value props for the email and password fields to allow use of state vars.

### ISSUE THREAD

**Issue by huperniketes** [WrathChaos/react-native-login-screen#129]
react-native-login-screen doesn't accept values for the email and password fields to be set by its enclosing component. It initializes and maintains internal vars for these fields.

As a result, any time an enclosing component is re-rendered by the React Native system the LoginScreen is reloaded and re-rendered as well, resetting the email and password input components to empty fields.

In addition, I notice if a user enters text into the password field, then selects the email field, and re-selects the password field and enters additional text, the previous contents of the password field will be deleted.

I suggest the addition of props to set the initial values of the email and password fields, which will allow LoginScreen to be used in components which require there use of state vars. This will also permit the password field to retain its value between selections, and the enclosing component to save a user's credentials between app openings.

**Comment by WrathChaos** [comment]
Helloo,
I can see that you have enough knowledge how to implement the suggestion from your side. I am happy to review and merge the PR :) 

Also, thank you for the suggestion, if you reject to contribute the library when I have time I can surely take a look at it

**Comment by huperniketes** [comment]
I'd be happy to contribute to the project. Right now I'm trying to figure out how to get a React Native app to successfully import a local repo in its build. Once I can do that with react-native-login-screen, I'll make the changes and ensure they work correctly before sending you a PR.

**Comment by WrathChaos** [comment]
@huperniketes 
I am not sure if I understand what you're trying to do but there is a script on the library itself. You can try it with npm run build and it will generate a library's build folder. You can simply copy paste this folder and test it out with any react native project.

**Comment by omerhochman** [comment]
I have the same issue, the text inputs are cleared everytime the user types. 

I've added the needed props in the following PRs using github editor:
https://github.com/WrathChaos/react-native-login-screen/pull/164
https://github.com/WrathChaos/react-native-login-screen/pull/165

**Comment by omerhochman** [comment]
@WrathChaos can you pls review them?

**Comment by WrathChaos** [comment]
Hello @omerhochman 
Thank you so much for contribution :) 

I actually reviewed them and looks good however [Version 5](https://github.com/WrathChaos/react-native-login-screen/tree/feat/version-5) is under development and almost over and it covers these issues as well. If you want to contribute, please take a look at the version 5 :)

**Comment by omerhochman** [comment]
Thank you @WrathChaos

I like the solution in Version 5 better :)
Allowing the user to send all props per input!

I suggest a small addition to prevent this issue by passing the value we already hold in state, instead of forcing the user to do it.
https://github.com/WrathChaos/react-native-login-screen/pull/167

**Comment by WrathChaos** [comment]
I commented on the PR :) If we will decide that I love to merge this PR

**Comment by WrathChaos** [comment]
### [Version 5](https://github.com/WrathChaos/react-native-login-screen/releases/tag/5.0.0) is released 🌟

It should support this feature as well please try it out 🥰
