### ISSUE TITLE
Enhancement Feature : Email Validation

### ISSUE THREAD

**Issue by programmersoham** [WrathChaos/react-native-login-screen#148]
After clicking submit button, email validation should be available in the package.

**Comment by WrathChaos** [comment]
Hello @programmersoham 
Everyone has a different approach or use-case for email validation so it should be out-of-the-box from this library. 

We cannot cover every use-case for email validation.

**Comment by WrathChaos** [comment]
Hello @programmersoham 

At the end I made your request and it is even customizable if you do not like the built-in email validation and even password validation :) 

### [Version 5](https://github.com/WrathChaos/react-native-login-screen/releases/tag/5.0.0) is released 🌟

It should support this feature as well please try it out 🥰
