### ISSUE TITLE
Want to add 1 more Password Field (to confirm password)

### ISSUE THREAD

**Issue by Seo-A-Nam** [WrathChaos/react-native-login-screen#162]
Hi.
First, I'd like to say i really appreciate this beautiful source code. This helps me so much.

Yet I wanted to make my project's Auth UI consistent, i tried to make SignUp UI as well out of this Login component. The only thing I wanted was to add one more password field to verify confirming password.

So I editted the source in ./node_modules to enable confirming password field by 'enableConfirmPassword' boolean flag. However, i soon found out it doesn't works with my changes. It didn't make any change that i couldn't find confirming password field appear.

By any chance, can you help me to fix this issue?

Below is my patch file.

```patch
diff --git a/node_modules/react-native-login-screen/build/dist/LoginScreen.d.ts b/node_modules/react-native-login-screen/build/dist/LoginScreen.d.ts
index 240170a..877bc89 100644
--- a/node_modules/react-native-login-screen/build/dist/LoginScreen.d.ts
+++ b/node_modules/react-native-login-screen/build/dist/LoginScreen.d.ts
@@ -13,6 +13,8 @@ export interface ILoginScreenProps {
     passwordPlaceholder?: string;
     disableSignup?: boolean;
     disablePasswordInput?: boolean;
+    enableConfirmPassword?: boolean;
+    confirmPasswordPlaceholder?: string;
     loginButtonText?: string;
     style?: CustomStyleProp;
     dividerStyle?: CustomStyleProp;
@@ -28,6 +30,7 @@ export interface ILoginScreenProps {
     onSignupPress: () => void;
     onEmailChange: (email: string) => void;
     onPasswordChange: (password: string) => void;
+    onConfirmPasswordChange : (confirmPassword: string) => void;
     onFacebookPress?: () => void;
     onTwitterPress?: () => void;
     onApplePress?: () => void;
diff --git a/node_modules/react-native-login-screen/lib/LoginScreen.tsx b/node_modules/react-native-login-screen/lib/LoginScreen.tsx
index e346f19..d614fdd 100644
--- a/node_modules/react-native-login-screen/lib/LoginScreen.tsx
+++ b/node_modules/react-native-login-screen/lib/LoginScreen.tsx
@@ -36,6 +36,8 @@ export interface ILoginScreenProps {
   passwordPlaceholder?: string;
   disableSignup?: boolean;
   disablePasswordInput?: boolean;
+  enableConfirmPassword?: boolean;
+  confirmPasswordPlaceholder?: string;
   loginButtonText?: string;
   style?: CustomStyleProp;
   dividerStyle?: CustomStyleProp;
@@ -51,6 +53,7 @@ export interface ILoginScreenProps {
   onSignupPress: () => void;
   onEmailChange: (email: string) => void;
   onPasswordChange: (password: string) => void;
+  onConfirmPasswordChange : (confirmPassword: string) => void;
   onFacebookPress?: () => void;
   onTwitterPress?: () => void;
   onApplePress?: () => void;
@@ -82,6 +85,9 @@ const LoginScreen: React.FC<ILoginScreenProps> = ({
   onDiscordPress = dummyFunction,
   emailPlaceholder = 'Email',
   passwordPlaceholder = 'Password',
+  enableConfirmPassword = false,
+  onConfirmPasswordChange,
+  confirmPasswordPlaceholder = 'Confirm Password',
   disableSignup = false,
   children,
   textInputProps,
@@ -111,6 +117,16 @@ const LoginScreen: React.FC<ILoginScreenProps> = ({
           />
         </View>
       )}
+      {enableConfirmPassword && (
+        <View style={styles.passwordTextInputContainer}>
+          <TextInput
+            placeholder={confirmPasswordPlaceholder}
+            secureTextEntry
+            onChangeText={onConfirmPasswordChange}
+            {...textInputProps}
+          />
+        </View>
+      )}
     </View>
   );
 
```

**Comment by WrathChaos** [comment]
Hello @Seo-A-Nam,
Thank you for the kind words and for using the library :) 

I am working on **Version 5** with more customization options and better code fundamentals with performance improvements. 

In version 5 you are going to be able to add new children in each part, so you will not have to do this patch stuff. 

Probably it will be available today or tomorrow :)

**Comment by WrathChaos** [comment]
Hellooo again @Seo-A-Nam 

It's finally here :) You can do whatever you want with the latest version 5 :) 

### [Version 5](https://github.com/WrathChaos/react-native-login-screen/releases/tag/5.0.0) is released 🌟

It should support this feature as well please try it out 🥰


Please also check the `example` project :)

**Comment by WrathChaos** [comment]
```tsx
<LoginScreen
      logoImageSource={require('./assets/logo-example.png')}
      onLoginPress={() => {}}
      onSignupPress={() => {}}
      onEmailChange={setUsername}
      loginButtonText={'Create an account'}
      disableSignup
      textInputChildren={
        <View style={{marginTop: 16}}>
          <TextInput
            placeholder="Re-Password"
            secureTextEntry
            onChangeText={setRepassword}
          />
        </View>
      }
      onPasswordChange={setPassword}
    />

```


You can use `textInputChildren` to add any of the components as you want

Please open another issue if you need help :)

**Comment by jwitthaus** [comment]
I appreciate your effort in providing version 5 and the option to add any children. But how do I provide the textfield with the same styling?

**Comment by jwitthaus** [comment]
Hi, thank you, but this doesn't work. It looks like this, where re-password
has a different style than password
 [image: image.png]

**Comment by WrathChaos** [comment]
@jwitthaus can you upload the image again?

**Comment by jwitthaus** [comment]
sure. Uploaded the picture again. Just tested you example and it is working, but why mine is not? Just copy pasted the component from the example. 

<img width="342" alt="Image" src="https://github.com/user-attachments/assets/5c74d308-59f6-4c79-9196-a86fe287ae7c" />

**Comment by jwitthaus** [comment]
sorry found the issue now. I need to import TextInput from "react-native-text-input-interactive"; instead of import TextInput from "react-native";

Thank you very much.
