### ISSUE TITLE
Icons don't show up

### ISSUE THREAD

**Issue by blessseeker** [WrathChaos/react-native-login-screen#18]
I hope this is not a silly question as i am currently new to react-native. After following your instruction, the application ran smoothly on my device. I can change the background, etc. The problem is that the github, user, password, and settings icons don't show up. Instead i got some chinese like letters. FYI i already installed react-native-dynamic-vector-icons and react-native-vector-icons. What could be the problem? What possibly i missed?

**Comment by WrathChaos** [comment]
Hello @blessseeker,
You need to setup the `react-native-vector-icons` correctly. If you're on the iOS simply copy-paste this on `info.plist`

```
<key>UIAppFonts</key>
<array>
  <string>AntDesign.ttf</string>
  <string>Entypo.ttf</string>
  <string>EvilIcons.ttf</string>
  <string>Feather.ttf</string>
  <string>FontAwesome.ttf</string>
  <string>FontAwesome5_Brands.ttf</string>
  <string>FontAwesome5_Regular.ttf</string>
  <string>FontAwesome5_Solid.ttf</string>
  <string>Foundation.ttf</string>
  <string>Ionicons.ttf</string>
  <string>MaterialIcons.ttf</string>
  <string>MaterialCommunityIcons.ttf</string>
  <string>SimpleLineIcons.ttf</string>
  <string>Octicons.ttf</string>
  <string>Zocial.ttf</string>
  <string>Fontisto.ttf</string>
</array>
```

If it still not works, please take a look at this: https://github.com/oblador/react-native-vector-icons#installation

Also, I will remove the icon and helper dependency nowadays :)

**Comment by WrathChaos** [comment]
@blessseeker I'm closing the issue, if you have still trouble please re-write this :) we can solve it together.
