### ISSUE TITLE
More Customizable Props

### ISSUE THREAD

**Issue by ameenmattar** [WrathChaos/react-native-login-screen#2]
Hello 👋 , Thank you for this awesome library.
Is there any props to disable the switch component if not needed same as settings(disableSettings) ?

**Comment by WrathChaos** [comment]
Hello @ameenmattar,
Thank you for this issue :) I'm going to add this feature ASAP. I will inform you when it is available.

**Comment by WrathChaos** [comment]
Hey again @ameenmattar 
Check this new release out :) 

## [Release 0.3.5 🎉](https://github.com/WrathChaos/react-native-login-screen/releases/tag/0.3.5)

If you have any other ideas or more customizable. Please open another issue :) Waiting for the new stuff
