### ISSUE TITLE
Defect

### ISSUE THREAD

**Issue by eze1376** [WrathChaos/react-native-login-screen#24]
when I change usernameTitle, passwordTitle it happens nothing!
I check the source code and it hasn't been implemented anything to customize this propery!

**Comment by WrathChaos** [comment]
Thank you so much for the reporting :) I will fix it today

**Comment by eze1376** [comment]
Thank you for providing this useful package :)

> Thank you so much for the reporting :) I will fix it today

**Comment by WrathChaos** [comment]
@eze1376 I fixed it with [version 2.1.4](https://freakycoder.com/git-cheat-sheet-for-daily-usage-3e479d8f6507)

**Comment by eze1376** [comment]
@WrathChaos I try the new version but it still use placeholder as title, too.

**Comment by WrathChaos** [comment]
@eze1376 You should clean the cache, it still uses the old version of the cache. Simple go to node_modules, find the react-native-login-screen and go to LoginScreen.js and simply save it. It should update the library itself. (Yea, weird bug weird solution 😕)
