### ISSUE TITLE
Please give me advice how to move screen onPressLogin

### ISSUE THREAD

**Issue by kuksundo** [WrathChaos/react-native-login-screen#43]
Hello,

Just want to change screen when pressed "Sign In" Button like below:
-------------------
```jsx
onPressLogin={()=>Home()}

const Home = () => {
  return (
              `<View`
                  `<Text>Home</Text>`
               `</View>`
    );
};
```

But login screen not changed when press button.

Please give me any advise.

**Comment by WrathChaos** [comment]
Hello @kuksundo,

You should use a navigation system such as; [`react-navigation`](https://reactnavigation.org) or [`react-native-navigation`](https://github.com/wix/react-native-navigation)

You can simply `Navigation.navigate("home")` and it will change the screen.

**Comment by kuksundo** [comment]
Thank you for your excellent login library.

As your advice, i had used a navigation as below:
...
      <Stack.Navigator>
        <Stack.Screen
          name="Login"
          component={LoginPage}
           options={{ title: 'Welcome' }}
        />
      </Stack.Navigator>
...

But "logIn" button as displayed bottom of screen is not displayed.

What am i solve this problem?
