### ISSUE TITLE
Dependency installing Error

### ISSUE THREAD

**Issue by Hiruni98** [WrathChaos/react-native-login-screen#45]
I tried to run your code, but unfortunately it does not work... can you please let me know how to configure and run it and get the desired output, for me to customise! When I try to add the dependency the following error comes?
![Screenshot from 2021-12-15 08-28-11](https://user-images.githubusercontent.com/45037925/146115077-811f7437-8930-48fc-9854-94e7fb530526.png)

**Comment by WrathChaos** [comment]
Hello again @Hiruni98,
This is actually the npm's issue. Can you try to downgrade your global npm to 6.x version and try again?
