### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by leitooop** [WrathChaos/react-native-login-screen#5]
I Really like your Login Screen! im trying to init a new App and after installing your library and dependencies screen is working except fot the icons

### package.json

```javascript

  "dependencies": {
    "@freakycoder/react-native-helpers": "^0.1.3",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-dynamic-vector-icons": "^0.1.1",
    "react-native-improved-text-input": "^0.0.1",
    "react-native-login-screen": "^0.3.7",
    "react-native-spinkit": "^1.5.0",
    "react-native-vector-icons": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

### Screenshot

![WhatsApp Image 2020-04-12 at 1 45 55 PM](https://user-images.githubusercontent.com/20303838/79074832-ed9ac980-7cc4-11ea-864b-b54091300a35.jpeg)

**Comment by WrathChaos** [comment]
Hello @leitooop,
Thank you for these kind words :) 
You need to run this command: 
`react-native link`
Close the bundler, and then re-run the command:
`react-native run-ios/android`

It should work with that :)

**Comment by leitooop** [comment]
Works like a charm now :) 

Just an opinion, but a sign up button would be usefull, every user must sign up first. 

and maybe choosing if the gear is visible or not as an option in the component, to keep it simple for most cases.

Great Work :)

**Comment by WrathChaos** [comment]
> Works like a charm now :)
> 
> Just an opinion, but a sign up button would be usefull, every user must sign up first.
> 
> and maybe choosing if the gear is visible or not as an option in the component, to keep it simple for most cases.
> 
> Great Work :)

Ah thank you for the suggestions :) I'm planning to add a sign up button but cannot find a good design to put it on this library.

Also you can disable the gear button with this prop: 
`disableSettings`

**Comment by leitooop** [comment]
Couple of ideas:

As a user i want the Login button to show"create account" but if i start filling username and password it changes to "login"  (because i already have an account)
( weird but  i think it will be intuitive )

I think in most of cases "Remember me" is not strictly necessary either. Becauso every time you enter the App it should remember your account as default. 
Maybe, simplifying the design taking out "remember me" gives space for "sign up"

A bit more ugly but aside of "login" making two buttons in that space ( "login" at left and "sign up" at right )

**Comment by WrathChaos** [comment]
Let's move this awesome idea collection to another issue :)
