### ISSUE TITLE
Using the library for register screen?

### ISSUE THREAD

**Issue by notimre** [WrathChaos/react-native-login-screen#51]
Hi,

I come from a native Swift background and I'm still trying to work my way around React Native.

I'm trying to create a register screen using this library, and not sure how I could add an extra text input for a username?
Any help would be appreciated, as I'm not sure how to customise it.

An off topic issue, any chance it's possible to change the selectionColour on the pre defined text inputs? As I can't find my way to style it with a different colour, only the base blue stays.

**Comment by WrathChaos** [comment]
### [Version 5](https://github.com/WrathChaos/react-native-login-screen/releases/tag/5.0.0) is released 🌟

It should support this feature as well please try it out 🥰

There is a much better support for this and there is an example for register screen on the existing example and readme :) 

@notimre
