### ISSUE TITLE
Cannot Use SocialButton component

### ISSUE THREAD

**Issue by alpha-ulrich** [WrathChaos/react-native-login-screen#53]
When trying to import SocialButton as:
import { SocialButton } from "react-native-login-screen"';

I am getting the following error:
Module '"react-native-login-screen"' has no exported member 'SocialButton'. Did you mean to use 'import SocialButton from "react-native-login-screen"' instead?

Importing in the manner the error message suggests (removing the curly braces around SocialButton) results in another error:
Type '{ text: string; imageSource: any; onPress: () => void; }' is not assignable to type 'IntrinsicAttributes & ILoginScreenProps & { children?: ReactNode; }'.
  Property 'text' does not exist on type 'IntrinsicAttributes & ILoginScreenProps & { children?: ReactNode; }'.ts

Any idea what needs to be fixed?

**Comment by WrathChaos** [comment]
[Version 3.1.0 🥳](https://github.com/WrathChaos/react-native-login-screen/releases/tag/3.1.0) version fixes this :) Please try it out @alpha-ulrich
