### ISSUE TITLE
Change 'have account' text to 'create account' text

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [WrathChaos/react-native-login-screen#54]
When logging in, you use a email and password, which is there. It doesn't make sense to have a button for already having an account, because they are already logging in. It would make more sense if the button said 'I don't have an account' or 'Sign Up'.

**Comment by WrathChaos** [comment]
Totally right :) I will make the change 

Thank you so much @ChocolateLoverRaj

**Comment by WrathChaos** [comment]
[Version 3.1.0 🥳](https://github.com/WrathChaos/react-native-login-screen/releases/tag/3.1.0) changes this part :) 

@ChocolateLoverRaj Please check it out

**Comment by ChocolateLoverRaj** [comment]
@WrathChaos 👍 it works, execpt changing the name of the props is a breaking change. People upgrading from 3.0 > 3.1 will be surprised to see that 'haveAccountText' doesn't work. Maybe it should've been version 4.0.0.

**Comment by WrathChaos** [comment]
@ChocolateLoverRaj  You're right 4.0.0 is published :) 

I should not publish new versions middle of the night :D
