### ISSUE TITLE
Customize email placeholder

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [WrathChaos/react-native-login-screen#55]
I want to change it from saying 'Email' to 'Usename'. I don't see any props currently that let me change that.

**Comment by WrathChaos** [comment]
Hey @ChocolateLoverRaj,
I totally forgot it. I will make it changeable :)

**Comment by WrathChaos** [comment]
[Version 3.1.0 🥳](https://github.com/WrathChaos/react-native-login-screen/releases/tag/3.1.0) have this options :) 

You can use `emailPlaceholder` and `passwordPlaceholder` and many more :) 

@ChocolateLoverRaj

**Comment by ChocolateLoverRaj** [comment]
@WrathChaos 👍 it works but in the README those props aren't there.

**Comment by WrathChaos** [comment]
Added them @ChocolateLoverRaj  :) Thanks
