### ISSUE TITLE
Issue with docs - SocialButton

### ISSUE THREAD

**Issue by LAyoung** [WrathChaos/react-native-login-screen#59]
Hi, just letting you know that the docs say to use SocialButton but SocialLogin is actually being exported from the library!

**Comment by WrathChaos** [comment]
OUCH 

What a miss, thank you so much for letting me know :) @LAyoung 

Fixing it asap!

**Comment by LAyoung** [comment]
No worries, thank you!

**Comment by WrathChaos** [comment]
Finally I fixed it :) 

## [Version 4.0.1 🚀 ](https://github.com/WrathChaos/react-native-login-screen/releases/tag/4.0.1)

Thank you again sir!
@LAyoung
