### ISSUE TITLE
Couple of Ideas by leitooop

### ISSUE THREAD

**Issue by WrathChaos** [WrathChaos/react-native-login-screen#6]
> Couple of ideas:
> 
> As a user i want the Login button to show"create account" but if i start filling username and password it changes to "login" (because i already have an account)
> ( weird but i think it will be intuitive )
> 
> I think in most of cases "Remember me" is not strictly necessary either. Becauso every time you enter the App it should remember your account as default.
> Maybe, simplifying the design taking out "remember me" gives space for "sign up"
> 
> A bit more ugly but aside of "login" making two buttons in that space ( "login" at left and "sign up" at right )

**Comment by WrathChaos** [comment]
@leitooop,
** Idea Number 1:** Actually this is a cool idea but it could be weird for the user also, it is doable right now. All you need to do is, check both username and password fields and handle the login - sign up button. 

**Idea Number 2:** Remember Me button would be unnecessary, I can convert it to "Sign Up" button to change the whole login screen to sign-up one like :

- Email
- Password 
- Re-password 

Sign-Up Button (Used to be Login Button)

(this is a huge work but I can do it if we decide it to :) 

------

**Idea Number 3:**  I do not like this idea actually, because the ugly design. Let's discuss the Idea No 2 :) 


What do you think @leitooop?

**Comment by leitooop** [comment]
sorry the late response, crazy days lately, im using your login page for a new idea, so if you need help going forward with Idea Number 2 i could help.

Right now im trying to implement Authentication with Firebase with your login page.

**Comment by leitooop** [comment]
i think the challenges are the function callbacks, maybe as you make this login page repo, could be another "component" that's the sign up page, if somwone need's it they just install the other library, and maybe putting some example will clarify the all thing together.

Maybe One component with login and sign up its just a lot.

what do you think?

**Comment by WrathChaos** [comment]
Hello @leitooop,
I've finally completed the new form system :) 
Please check this version 1.0.0 :)

# [Release 1.0.0](https://github.com/WrathChaos/react-native-login-screen/releases/tag/1.0.0)
#
Version 1.0.0: Fully customizable and battle-hardened 🥳 🎉

* Fully customizable options
* Battle-hardened & Tested
* Built-in spinner system
* Sign-up and login form system


#7 Fixed the Android design problem
