### ISSUE TITLE
Login button too down on Android

### ISSUE THREAD

**Issue by xlucxs** [WrathChaos/react-native-login-screen#7]
**On startup, the login button touch the bottom**

![image](https://user-images.githubusercontent.com/42546473/83120566-82208600-a0d1-11ea-80ad-e00610d8e0b2.png)

**When you enter one of the two inputs and flip the login button it places perfectly**

![image](https://user-images.githubusercontent.com/42546473/83120736-b6944200-a0d1-11ea-81f4-5b591ea4dbc5.png)

![image](https://user-images.githubusercontent.com/42546473/83120892-eba09480-a0d1-11ea-8b00-a2b58b3a1fb7.png)

**Does anyone know how to fix this? Thank you very much.**

**Comment by WrathChaos** [comment]
I will fix it today :) Thank you, I will inform you when it is done

**Comment by WrathChaos** [comment]
Hello @xlucxs,
I've released a new version: 
[v1.0.0](https://github.com/WrathChaos/react-native-login-screen/releases/tag/1.0.0)

Also fixed the Android problem :) Please test it out :)
