### ISSUE TITLE
How to get entered email/password?

### ISSUE THREAD

**Issue by Hyllesen** [WrathChaos/react-native-login-screen#83]
This is a pretty basic question, but I can't figure out how to get the entered email/password. Should I store the email in state, or can it be sent with onLoginPress() ?

If I try to use setEmail during onEmailChange, the email input will not update. 

If I try getting values from onLoginPress, I get this node object, but I don't see any values in e.target.value for example.

Here's my example:

```
import React, {useState} from 'react';
import {Alert} from 'react-native';

import LoginScreen from 'react-native-login-screen';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  function login(test) {
    Alert.alert('login, ' + email + password);
  }

  return (
    <LoginScreen
      logoImageSource={require('../assets/ikon.png')}
      onLoginPress={() => login()}
      onEmailChange={email => setEmail(email)} //Doesn't work
      disableSignup
      disableSocialButtons
    />
  );
}
```

**Comment by halitpeker** [comment]
onEmailChange={(username) => { state.username = username; }}
onPasswordChange={(password) => { state.password = password; }}

**Comment by Hyllesen** [comment]
> onEmailChange={(username) => { state.username = username; }} onPasswordChange={(password) => { state.password = password; }}

Where is this state variable coming from?

**Comment by Hyllesen** [comment]
> onEmailChange={(username) => { state.username = username; }} onPasswordChange={(password) => { state.password = password; }}

You're not supposed to modify state directly like that: 
https://reactjs.org/docs/state-and-lifecycle.html

**Comment by WrathChaos** [comment]
Helloo,
Sorry for late response. 
You're totally right actually, my example is totally wrong. We have two options to make it work smoothly. [I will update the example]

```typescript
const App = () => {
  let username = '';
  const [switchValue, setSwitchValue] = useState(false);
  const [spinnerVisibility, setSpinnerVisibility] = useState(false);

  return (
    <View style={{flex: 1}}>
      <StatusBar barStyle="light-content" />
      <LoginScreen
        logoImageSource={require('./assets/logo-example.png')}
        onLoginPress={() => {}}
        onSignupPress={() => {}}
        onEmailChange={(value: string) => {
          username = value;
          console.log('username: ', username);
        }}
        onPasswordChange={(password: string) => {}}
      />
    </View>
  );
};
```

We can simply create a variable and store the value on this variable. Like this example's `username` variable. You can simply use this variable as you want. 


OR

You can wrap this with a Stateful Component (aka Class Component) and use the this.state to set the values from input to prevent the re-render for each input changes. 

If you have a better solution please share with me :) Love to learn

**Comment by WrathChaos** [comment]
Hello again @Hyllesen 
Now, it supports much better way to use `useState` with the version 5 :) 

### [Version 5](https://github.com/WrathChaos/react-native-login-screen/releases/tag/5.0.0) is released 🌟

It should support this feature as well please try it out 🥰
