### ISSUE TITLE
Support custom props for TextInput

### ISSUE THREAD

**Issue by pasdoy** [WrathChaos/react-native-login-screen#9]
Hi ! Thank you for this awesome library. 

I would like to add support for custom props to Username and Password TextInput to support the following use case:

```
autoCapitalize="none"
autoCompleteType="email"
autoCorrect={false}
keyboardType="email-address"
```

What would be the best way to add this feature ? Adding `usernameTextInputProps` and `passwordTextInputProps` ?

**Comment by WrathChaos** [comment]
Hello @pasdoy,
Actually the way is to send `...this.props` but it crashes some of the props. We need to add these props manually and handle it. Can you open a PR for that?

**Comment by Notorious112** [comment]
I would also recommend having returnKeyType="next" for the first text input  and focus the next one which will have returnKeyType="go". Of course pressing "go" would fire the login button function. 

However, i'm not sure if improved-text-input properly supports the latest React Native version's ref.

**Comment by WrathChaos** [comment]
Hello @Notorious112,
I will handle it if it does not support. Also, I'm considering to remove some of the dependencies.  I will add more features for the TextInput ASAP. 

Of course, PR's are welcome :)

**Comment by WrathChaos** [comment]
Hey again @Notorious112 and @pasdoy,
Please try the newest version of the library: 2.0.3.

It has a complete new textinput (actually textfield) :) If you still need any more customization please open another issue :)
