### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by na5la77** [WrathChaos/react-native-login-screen#96]
Hello, I am trying to make a dark mode design for my app but i am not able to change the background colors of the input text fields, any tips?

**Comment by WrathChaos** [comment]
Hello @na5la77 
You're right! 
I will make it customizable today :)

**Comment by WrathChaos** [comment]
Hello again @na5la77 
You can customize TextInputs whichever you want with the version of

## [4.2.0 😍](https://github.com/WrathChaos/react-native-login-screen/releases/tag/4.2.0)

You can use the `textInputProps`, like this: 

```jsx
textInputProps={{
   textInputStyle: {
        backgroundColor: '#ccc',
   },
 }}
```

Please try it out :)

**Comment by na5la77** [comment]
Thank you :D
